doctrine:
    dbal:
        #driver: sqlsrv
        #host: srv-poc-bo\poc_bo
        #user: imm_dw
        #password: imm_dw
        #dbname: IMM_DW
        #port: 1433
        #charset: UTF-8
        #schema_filter: $CLI_MVT_PAT$
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App