USE [IMM_DW]
GO

/****** Object:  Table [dbo].[THYMUS_FORM_PATIENT]    Script Date: 31/12/2020 14:14:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[THYMUS_FORM_PATIENT](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[prenom] [nvarchar](255) NOT NULL,
	[nom] [nvarchar](255) NOT NULL,
	[ddn] [datetime2](6) NOT NULL,
	[sexe] [nvarchar](10) NOT NULL,
	[poids] [float] NULL,
	[taille] [float] NULL,
	[chirurgien_referent] [nvarchar](255) NOT NULL,
	[ps] [nvarchar](10) NULL,
	[mode_de_decouverte] [nvarchar](255) NULL,
	[mode_obt_his_pre_ope] [nvarchar](255) NULL,
	[histo_pre_op] [nvarchar](255) NULL,
	[indication] [nvarchar](255) NULL,
	[cons_neu_dep_mg_pre_op] [nvarchar](255) NULL,
	[score_myast_pre_op] [int] NULL,
	[irm] [nvarchar](255) NULL,
	[tdm] [nvarchar](255) NULL,
	[petscan] [nvarchar](255) NULL,
	[chimio_pre_op] [nvarchar](255) NULL,
	[reponse_chimio_pre_op] [nvarchar](255) NULL,
	[x_tnm] [nvarchar](255) NULL,
	[tnm_t] [nvarchar](255) NULL,
	[tnm_n] [nvarchar](255) NULL,
	[tnm_m] [nvarchar](255) NULL,
	[tnm_stade_ctnm] [nvarchar](255) NULL,
	[stade_masaoka_pre_op] [nvarchar](255) NULL,
	[maladi_auto_imm_assoc] [nvarchar](255) NULL,
	[syndrome_paraneo] [nvarchar](255) NULL,
	[epp] [nvarchar](255) NULL,
	[anticorps_anti_rach] [nvarchar](255) NULL,
	[rcp_rythmique] [nvarchar](255) NULL,
	[chir_date_ope] [datetime2](6) NULL,
	[chir_abord] [nvarchar](255) NULL,
	[chir_thoracos] [nvarchar](255) NULL,
	[chir_robo_assist] [nvarchar](255) NULL,
	[chir_geste] [nvarchar](255) NULL,
	[commentaire] [varchar](max) NULL,
	[insufflation_co2] [nvarchar](255) NULL,
	[conversion] [nvarchar](255) NULL,
	[chir_duree] [nvarchar](10) NULL,
	[chir_sang] [nvarchar](10) NULL,
	[mortalite_par_ope] [nvarchar](255) NULL,
	[complication_pre_ope] [varchar](max) NULL,
	[chir_drainage] [nvarchar](50) NULL,
	[chir_interv_interac] [nvarchar](10) NULL,
	[qualite_resection] [nvarchar](255) NULL,
	[anapath_post_op] [nvarchar](255) NULL,
	[pre_op_x_tnm] [nvarchar](255) NULL,
	[post_tnm_t] [nvarchar](255) NULL,
	[post_tnm_n] [nvarchar](255) NULL,
	[post_tnm_m] [nvarchar](255) NULL,
	[post_tnm_stade_ctnm] [nvarchar](255) NULL,
	[rea_usc_post_op] [nvarchar](255) NULL,
	[post_op_suites] [nvarchar](255) NULL,
	[post_op_duree_drainage] [int] NULL,
	[pre_op_duree_rea] [int] NULL,
	[post_op_date_sortie] [datetime2](6) NULL,
	[chimio_post_op] [nvarchar](255) NULL,
	[radiotherapie_post_op] [nvarchar](255) NULL,
	[date_der_nouvelles] [datetime2](6) NULL,
	[suivi_myasthenie] [varchar](max) NULL,
	[score_mya_post_op] [int] NULL,
	[recidive] [nvarchar](10) NULL,
	[date_recidive] [datetime2](6) NULL,
	[localisation_recidive] [varchar](max) NULL,
	[traitement_rechute_recidive] [varchar](max) NULL,
	[num_acp] [varchar](max) NULL,
	[deces] [nvarchar](10) NULL,
	[cause_deces] [nvarchar](255) NULL,
	[elios] [int] NULL,
	[date_diag_acp] [datetime2](6) NULL,
	[id_acp] [nvarchar](255) NULL,
	[tissu_congele] [nvarchar](10) NULL,
	[score_charlson] [nvarchar](255) NULL,
	[autre_histo_pre_op] [nvarchar](255) NULL,
	[autre_mode_obt_his_pre_ope] [nvarchar](255) NULL,
	[autre_cons_neu_dep_mg_pre_op] [nvarchar](255) NULL,
	[trai_fond_myasthenie] [nvarchar](100) NULL,
	[autre_trai_fond_myasthenie] [nvarchar](255) NULL,
	[autre_irm] [nvarchar](255) NULL,
	[autre_tdm] [nvarchar](100) NULL,
	[autre_petscan] [nvarchar](255) NULL,
	[autre_tnm_t] [nvarchar](255) NULL,
	[autre_tnm_n] [nvarchar](255) NULL,
	[autre_tnm_m] [nvarchar](255) NULL,
	[autre_stade] [nvarchar](255) NULL,
	[autre_chir_geste] [nvarchar](255) NULL,
	[autre_anapath_post_op] [nvarchar](255) NULL,
	[autre_post_tnm_t] [nvarchar](255) NULL,
	[autre_post_tnm_n] [nvarchar](255) NULL,
	[autre_post_tnm_m] [nvarchar](255) NULL,
	[autre_post_tnm_stade_ctnm] [nvarchar](255) NULL,
	[autre_rea_usc_post_op] [nvarchar](255) NULL,
	[duree_rean] [nvarchar](255) NULL,
	[autre_post_op_suites] [nvarchar](255) NULL,
	[autre_chirurgien_referent] [nvarchar](255) NULL,
	[file_anapath_post_op] [nvarchar](255) NULL,
	[file_chirurgie] [nvarchar](255) NULL,
	[date_create] [datetime2](6) NOT NULL,
	[date_update] [datetime2](6) NULL,
	[user_create] [nvarchar](255) NULL,
	[user_update] [nvarchar](255) NULL,
	[reste_riques] [nvarchar](255) NULL,
	[chir_txt_libre] [nvarchar](255) NULL,
	[vcs] [bit] NULL,
	[hta] [bit] NULL,
	[tvi] [bit] NULL,
	[od] [bit] NULL,
	[og] [bit] NULL,
	[aorte] [bit] NULL,
	[pericard] [bit] NULL,
	[phreniqued] [bit] NULL,
	[phreniqueg] [bit] NULL,
	[wedge] [bit] NULL,
	[lobectomie] [bit] NULL,
	[pneug] [bit] NULL,
	[pneud] [bit] NULL,
	[avc] [bit] NULL,
	[ap] [bit] NULL,
	[obesite] [bit] NULL,
	[dyslipide] [bit] NULL,
	[diabete] [bit] NULL,
	[ins_ren_chr] [bit] NULL,
	[maladie_thro_vein] [bit] NULL,
	[cancer] [bit] NULL,
	[cardiopathie] [bit] NULL,
	[tabagisme] [bit] NULL,
	[kystique] [bit] NULL,
	[non_kystique] [bit] NULL,
	[solide] [bit] NULL,
	[mixte] [bit] NULL,
	[nonrealise] [bit] NULL,
	[donneeinconnue] [bit] NULL,
	[deces_che] [bit] NULL,
	[pousse] [bit] NULL,
	[paralysie] [bit] NULL,
	[paralysie_cur] [bit] NULL,
	[pneumopatie] [bit] NULL,
	[bullage] [bit] NULL,
	[decollement] [bit] NULL,
	[saignement] [bit] NULL,
	[infection] [bit] NULL,
	[lobectomie_txt] [nvarchar](100) NULL,
	[wedge_txt] [nvarchar](100) NULL,
	[cancer_txt] [nvarchar](100) NULL,
	[cardiopathie_txt] [nvarchar](100) NULL,
	[tabagisme_txt] [nvarchar](100) NULL,
	[tissulaire] [bit] NULL,
	[homogene] [bit] NULL,
	[regulier] [bit] NULL,
	[limiter] [bit] NULL,
	[diag_acp_thymone] [varchar](max) NULL,
	[masaoka_post_op] [nvarchar](50) NULL,
	[masaoko_koga] [nvarchar](50) NULL,
	[ttt_pre_op] [nvarchar](70) NULL,
	[autre_preop] [nvarchar](50) NULL,
	[complication_post_op] [nvarchar](100) NULL,
	[ttt_post_op] [nvarchar](100) NULL,
	[co_chirurgie] [bit] NULL,
	[co_diabete] [bit] NULL,
	[co_chirurgie_txt] [nvarchar](50) NULL,
	[co_diabete_txt] [nvarchar](50) NULL,
	[co_respiratoire] [bit] NULL,
	[co_respiratoire_txt] [nvarchar](50) NULL,
	[epp_autre] [nvarchar](100) NULL,
	[anticr_autre] [nvarchar](100) NULL,
	[tdm_autre] [nvarchar](100) NULL,
	[petscan_autre] [nvarchar](100) NULL,
	[is_active] [bit] NULL,
	[ipp] [nvarchar](100) NOT NULL,
	[commentaire_last] [varchar](max) NULL,
	[rcp_rythmique_date] [date] NULL,
	[is_valide_ipp] [bit] NULL,
	[service_adresseur] [nvarchar](255) NULL,
	[maladie_auto_immune_liste] [nvarchar](255) NULL,
	[service_adresseur_autre] [nvarchar](255) NULL,
	[is_in_conflict] [bit] NULL,
	[autre_chir_abord] [nvarchar](100) NULL,
	[dossier_pre_preop] [nvarchar](50) NULL,
	[interv_convfor_rcp] [nvarchar](50) NULL,
	[dossier_pre_post] [nvarchar](50) NULL,
	[decision_con_rcp] [nvarchar](50) NULL,
	[patient_in_protocole] [nvarchar](50) NULL,
	[comm_inter_conf_rcp] [varchar](max) NULL,
	[comm_deci_con_rcp] [varchar](max) NULL,
	[comm_pat_in_protocole] [varchar](max) NULL,
	[comm_decom_post] [varchar](max) NULL,
	[immuno_preop] [nvarchar](50) NULL,
	[decomp_post] [bit] NULL,
PRIMARY KEY CLUSTERED
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
